### ISSUE TITLE
关于评论模块Valine的安全性问题

### ISSUE THREAD

**Issue by dragonbra** [keybrl/blog#1]
您好！我读了您的博客，对Fluid这个主题很喜欢，打算参照您的博客配置一下自己的hexo博客。
但是发现您在主题Fluid的config.yml中留下了Valine的appid和appkey，特地来提醒一下……注意安全！可以考虑加入.gitignore之类的？

**Comment by keybrl** [comment]
已修复，感谢提醒

**Comment by keybrl** [comment]
@dragonbra 
其实屏蔽了这个配置文件也没有什么用，到前端 js 里翻一翻就能翻到，我去 leancloud 看了一下这些凭据的使用方式，看起来直接公开一般问题也不大。 ignore 之后发布还变得麻烦，要另外拉取私密配置

![image](https://user-images.githubusercontent.com/24802600/126064467-a7464681-d807-407d-9870-cec41a8d8d32.png)
